# <font color = red> Numpy

In [1]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

---
## <font color = blue> Create a Numpy array</font>
---
    
### 1.1 Using `np.array()`

In [2]:
# Create a numpy array

np_arr = np.array([[11,23,32],[12,34,56],[77,77,54]])
print(np_arr)
print()
print(np_arr.shape)

[[11 23 32]
 [12 34 56]
 [77 77 54]]

(3, 3)


In [3]:
np_arr = np.array([[11,23,32],[12,34,56],[77,77]])
print(np_arr)
print()
print(np_arr.shape)

[list([11, 23, 32]) list([12, 34, 56]) list([77, 77])]

(3,)


In [4]:
np_arr = np.array([[11,23,32],[12,34,56],[77,77,None]])
print(np_arr)
print()
print(np_arr.shape)

[[11 23 32]
 [12 34 56]
 [77 77 None]]

(3, 3)


### 1.2 `np.zeros() and np.ones()`

In [17]:
np_zeros = np.zeros([2,4])
np_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np_ones = np.ones([2,4])
np_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 1.3 `np.full()`

In [19]:
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

### 1.4 `np.arange()`


In [20]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 1.5 `np.linspace()`

the `linspace()` function generates an array with evenly spaced values between specified start, end values, using a specified number of elements

In [22]:
np.linspace(0, 1, 5)

array([0., 0., 0., 1., 1.])

In [23]:
np.linspace(0, 1, 20)
# 20 points equally spaced between 0 and 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [24]:
np.linspace(0, 1, 20, False)
# 20 points equally spaced between 0 and 1, not including 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

### 1.6 `identity`

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.7 `np.random()` 

In [26]:
np.random.random(size=2)
# Return random floats in the half-open interval [0.0, 1.0).
# Results are from the “continuous uniform” distribution over the stated interval.

array([0., 1.])

In [27]:
np.random.normal(size=2)
# creates an array of specified shape and fills it with random values which 
# is actually a part of Normal(Gaussian)Distribution. 
# This is Distribution is also known as Bell Curve because of its characteristics shape.

# https://www.geeksforgeeks.org/rand-vs-normal-numpy-random-python/

array([1., 1.])

In [30]:
arr = np.random.randint(2,10, size =(3,3) )  # 9 random numbers between 2 and 10 in a 3x3 matrix
arr

array([[4, 9, 4],
       [4, 8, 8],
       [9, 9, 4]])

In [33]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([5, 9, 2, 0, 6, 4, 3, 8, 7, 1])

In [35]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.random.shuffle(arr)
arr

array([5, 0, 4, 1, 6, 3, 2, 7, 8, 9])

In [37]:
np.random.rand(2, 4)

array([[1., 0., 1., 1.],
       [0., 0., 1., 0.]])

### 1.1  - Create a 1D array of the first 1000 odd numbers

In [38]:
print(np.linspace(1,1999,1000))

[1.e+00 3.e+00 5.e+00 7.e+00 9.e+00 1.e+01 1.e+01 2.e+01 2.e+01 2.e+01
 2.e+01 2.e+01 2.e+01 3.e+01 3.e+01 3.e+01 3.e+01 4.e+01 4.e+01 4.e+01
 4.e+01 4.e+01 4.e+01 5.e+01 5.e+01 5.e+01 5.e+01 6.e+01 6.e+01 6.e+01
 6.e+01 6.e+01 6.e+01 7.e+01 7.e+01 7.e+01 7.e+01 8.e+01 8.e+01 8.e+01
 8.e+01 8.e+01 8.e+01 9.e+01 9.e+01 9.e+01 9.e+01 1.e+02 1.e+02 1.e+02
 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02
 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02
 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02
 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02
 3.e+0

In [218]:
np.set_printoptions(formatter={'float_kind' : '{:f}'.format})
print(np.linspace(1,1999,1000))

[1.000000 3.000000 5.000000 7.000000 9.000000 11.000000 13.000000
 15.000000 17.000000 19.000000 21.000000 23.000000 25.000000 27.000000
 29.000000 31.000000 33.000000 35.000000 37.000000 39.000000 41.000000
 43.000000 45.000000 47.000000 49.000000 51.000000 53.000000 55.000000
 57.000000 59.000000 61.000000 63.000000 65.000000 67.000000 69.000000
 71.000000 73.000000 75.000000 77.000000 79.000000 81.000000 83.000000
 85.000000 87.000000 89.000000 91.000000 93.000000 95.000000 97.000000
 99.000000 101.000000 103.000000 105.000000 107.000000 109.000000
 111.000000 113.000000 115.000000 117.000000 119.000000 121.000000
 123.000000 125.000000 127.000000 129.000000 131.000000 133.000000
 135.000000 137.000000 139.000000 141.000000 143.000000 145.000000
 147.000000 149.000000 151.000000 153.000000 155.000000 157.000000
 159.000000 161.000000 163.000000 165.000000 167.000000 169.000000
 171.000000 173.000000 175.000000 177.000000 179.000000 181.000000
 183.000000 185.000000 187.000000 189.00

### 1.2  - Create a 2D array of size (5,10) containing random numbers between 1 and 2

In [39]:
np.random.rand(5,10)+1

array([[1., 1., 1., 2., 2., 2., 2., 2., 1., 1.],
       [2., 2., 2., 2., 1., 1., 1., 2., 2., 1.],
       [1., 1., 1., 2., 1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 2., 1., 1., 1., 2., 2., 1.],
       [2., 1., 2., 2., 2., 1., 1., 2., 2., 2.]])

### 1.3 - Create a 10x10 Identity matrix where all the numbers are in integer format

In [40]:
np.identity(10, dtype='int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

There are multiple ways in which numpy arrays can be created:

- np.array()
- np.ones() / np.zeros()
- np.full()
- np.arange()
- np.linspace()
- np.identity()
- np.random()

---
## <font color = blue> Reshape the array</font>
---    

### 2.1 `np_array.reshape()`

In [41]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
np.arange(12).reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

### 2.2 `arr.flatten()`

In [48]:
arr = np.array([[10,20,30],[40,50,60],[18,18,18]])
print(arr.flatten().shape)
print(arr.flatten())

(9,)
[10 20 30 40 50 60 18 18 18]


In [49]:
type(arr.flatten())

numpy.ndarray

In [ ]:
np.flatten()

### 2.3 `np.ravel()`

In [50]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [18, 18, 18]])

In [52]:
# Return a contiguous flattened array.

arr_ravel = np.ravel(arr)  
print(arr_ravel)

[10 20 30 40 50 60 18 18 18]


In [56]:
# Row-wise
np.ravel(arr, order='C')

array([10, 20, 30, 40, 50, 60, 18, 18, 18])

In [57]:
# Column-wise
np.ravel(arr, order='F')

array([10, 40, 18, 20, 50, 18, 30, 60, 18])

### 2.1 - Find the transpose of the given array without using `np.transpose`

In [64]:
arr = np.arange(50)
print(arr.shape)

(50,)


In [66]:
arr = arr.reshape(50,1)
print(arr.shape)

(50, 1)


### 2.2 Convert the following 2-D array into a 1-D array in columnar fashion (the first few elements should belong to the first column)

In [68]:
arr = np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
np.ravel(arr, order='F')

array([ 0, 10, 20, 30, 40,  1, 11, 21, 31, 41,  2, 12, 22, 32, 42,  3, 13,
       23, 33, 43,  4, 14, 24, 34, 44,  5, 15, 25, 35, 45,  6, 16, 26, 36,
       46,  7, 17, 27, 37, 47,  8, 18, 28, 38, 48,  9, 19, 29, 39, 49])

The following commands can be used to reshape the array

- np.reshape()
- np.ravel()
- np.flatten()

The one command np.reshape() is enough to perform all reshaping operations. The other two are just good to know if you want to flatten a dataset in a single command, without inspecting it first.

---
## <font color=blue>  Join and stack two arrays</font>
---

- Vertical stacking (row wise) using `vstack()`
- Horizontal stacking (column wise) using `hstack()`
- Depth wise stacking (along third axis) using `dstack()`
- `concatenate()` function creates a new array by appending arrays after each other, along a given axis
- `append()` function appends an element to an array and creates a new copy of the array


In [70]:
import numpy as np


array_1 = np.arange(10).reshape(2,5)
print(array_1)

print("-"*30)

array_2 = np.arange(13,23,1).reshape(2,5)
print(array_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
[[13 14 15 16 17]
 [18 19 20 21 22]]


### 3.1 `np.vstack()`

In [71]:
array_vstack = np.vstack([array_1,array_2])
print(array_vstack)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [13 14 15 16 17]
 [18 19 20 21 22]]


In [72]:
print(array_vstack.shape)

(4, 5)


### 3.2 `np.hstack()`

In [73]:
array_hstack = np.hstack([array_1,array_2])
print(array_hstack)

[[ 0  1  2  3  4 13 14 15 16 17]
 [ 5  6  7  8  9 18 19 20 21 22]]


In [74]:
print(array_hstack.shape)

(2, 10)


In [128]:
print(array_1)
print("-"*30)
print(array_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
[[13 14 15 16 17]
 [18 19 20 21 22]]


### 3.3 `np.dstack()`

In [75]:
array_dstack = np.dstack([array_1,array_2])
print(array_dstack)

[[[ 0 13]
  [ 1 14]
  [ 2 15]
  [ 3 16]
  [ 4 17]]

 [[ 5 18]
  [ 6 19]
  [ 7 20]
  [ 8 21]
  [ 9 22]]]


In [76]:
print(array_dstack.shape) # two sets of 5x2 matrices

(2, 5, 2)


### 3.4 `np.concatenate()`

In [77]:
array_concatenate = np.concatenate([array_1,array_2])
print(array_concatenate)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [13 14 15 16 17]
 [18 19 20 21 22]]


In [78]:
print(array_concatenate.shape) # same as vstack

(4, 5)


### 3.5 `np.append()`

In [79]:
array_append = np.append(array_1,array_2)
print(array_append)

[ 0  1  2  3  4  5  6  7  8  9 13 14 15 16 17 18 19 20 21 22]


In [80]:
print(array_append.shape)

(20,)


In [81]:
array_append = np.append(array_1,array_2,axis =1)
print(array_append)

[[ 0  1  2  3  4 13 14 15 16 17]
 [ 5  6  7  8  9 18 19 20 21 22]]


In [82]:
print(array_append.shape)

(2, 10)


In [83]:
array_append = np.append(array_1,array_2,axis = 0)
print(array_append)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [13 14 15 16 17]
 [18 19 20 21 22]]


In [84]:
print(array_append.shape)

(4, 5)


### 3.1 Represent the chess board as a numpy array
The following are the numerical mapping to chess pieces:
- Pawns: 1
- Rook: 2
- Knight: 3
- Bishop: 4
- King: 5
- Queen: 6
- Empty spaces: 0

In [86]:
row_1 = [2,3,4,5,6,4,3,2]
row_2 = np.ones(8,dtype=int)
row_3_4 = np.zeros(16,dtype=int).reshape(2,8)
top_half = np.vstack([row_1,row_2,row_3_4])
print(top_half)

[[2 3 4 5 6 4 3 2]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [89]:
bottom_half = np.flip(top_half,axis = 0)
print(bottom_half)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [2 3 4 5 6 4 3 2]]


In [85]:
row_1 = [2,3,4,5,6,4,3,2]
row_2 = np.ones(8,dtype=int)
row_3_4 = np.zeros(16,dtype=int).reshape(2,8)
top_half = np.vstack([row_1,row_2,row_3_4])
bottom_half = np.flip(top_half,axis = 0)

chess_board = np.vstack([top_half,bottom_half])
chess_board

array([[2, 3, 4, 5, 6, 4, 3, 2],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 3, 4, 5, 6, 4, 3, 2]])

### 3.2 Create an array of size 10x10 ,where the borders are all ones and the inside elements are zeros

In [105]:
arr = np.zeros(100, dtype=int).reshape(10,10)
print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [106]:
arr[0 , :] = arr[-1 , : ] = arr[ : , 0] = arr[ : , -1] = 1
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [114]:
arr = np.ones(100, dtype=int).reshape(10,10)
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [115]:
arr[1:-1 , 1:-1] = 0
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Any two arrays can be joined in the following formats:
- vstack() - Vertical stacking (row wise)
- hstack() - Horizontal stacking (column wise)
- dstack() - Depth wise stacking (along third axis)
- concatenate() - Creates a new array by appending arrays after each other, along a given axis
- append() - Appends an element to an array and creates a new copy of the array


In [123]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [122]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr.flatten().shape)

(6,)


In [124]:
arr1 = np.array([[0,0],[0,0]])
arr2 = np.array([[1],[1]])
arr3 = np.array([1,1,1])

In [126]:
arr4 = np.hstack([arr1,arr2])
print(np.vstack([arr4,arr3]))

[[0 0 1]
 [0 0 1]
 [1 1 1]]


---
## <font color = blue> Perform basic Slicing and Indexing</font>
---

### 4.1 `Location based indexing`

In [136]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [137]:
print(arr[0])

[10 20 30]


In [138]:
print(arr[0][0])

10


In [139]:
print(arr[0,0])

10


In [140]:
print(arr[-1])

[70 80 90]


In [141]:
print(arr[:,1:3])

[[20 30]
 [50 60]
 [80 90]]


In [142]:
print(arr[[0,1,2],[1,0,0]])

[20 40 70]


### 4.2 `Boolean Indexing`

### `np.where(  )`

- Returns the index based on the boolean

### `np.isnan()` 
- Returns the boolean of data == np.nan

In [143]:
location = np.array(["Mumbai","Mumbai","Delhi","Chennai","Bangalore"]) #2 branches in Mumbai
sales_data = np.random.randint(1,10,size=(5,5))
sales_data = sales_data.astype(float)
sales_data[[[1,4],[2,3]]] = np.nan
print(sales_data)

[[ 7.  3.  5.  9.  9.]
 [ 9.  1. nan  1.  2.]
 [ 8.  3.  2.  2.  8.]
 [ 6.  2.  6.  5.  2.]
 [ 3.  7.  5. nan  5.]]


In [144]:
sales_data[location =="Mumbai"]
# depending on which index is True, it prints that row
# In this case, mumbai is at index 2, therefore row no. 2 will be printed

array([[ 7.,  3.,  5.,  9.,  9.],
       [ 9.,  1., nan,  1.,  2.]])

In [145]:
(location =="Mumbai")

array([ True,  True, False, False, False])

In [146]:
np.where(location == "Mumbai")

(array([0, 1], dtype=int64),)

In [147]:
# if the match does not happen , then all values are false.
sales_data[location =="Kolkata"]
# the o/p in such a case is indicating shape as(0 rows, 3 features)

array([], shape=(0, 5), dtype=float64)

We can also use Boolean indexing for selecting some elements of an array that satisfy a
particular condition. For example, in the previous array suppose we want to only select
non-zero elements.
We can do that easily using the following code.

In [148]:
sales_data >4

array([[ True, False,  True,  True,  True],
       [ True, False, False, False, False],
       [ True, False, False, False,  True],
       [ True, False,  True,  True, False],
       [False,  True,  True, False,  True]])

In [149]:
sales_data == np.nan

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

`np.nan==np.nan` is always `False`

We use np.isnan() to find out the nan values in the data

In [150]:
np.isnan(sales_data)

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [151]:
np.where(np.isnan(sales_data))

(array([1, 4], dtype=int64), array([2, 3], dtype=int64))

In [152]:
sales_data[np.isnan(sales_data)] = 0.0 # all nan values will be reset to 0
sales_data

array([[7., 3., 5., 9., 9.],
       [9., 1., 0., 1., 2.],
       [8., 3., 2., 2., 8.],
       [6., 2., 6., 5., 2.],
       [3., 7., 5., 0., 5.]])

### 4.3 `np.ndenumerate()`

ndenumerate return the co-ordinates and corresponding values in the co-ordinates

In [153]:
A = np.array([[11, 22, 23], [33, 43, 55]])

In [154]:
np.ndenumerate(A)

In [155]:
for index, x in np.ndenumerate(A):
    print(index, x)

(0, 0) 11
(0, 1) 22
(0, 2) 23
(1, 0) 33
(1, 1) 43
(1, 2) 55


### 4.1 - Create a 1D array of alternating 0's and 1's of size 500

In [156]:
arr = np.zeros(500,dtype=int)
arr[1::2]=1
arr

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,

### 4.2 - Remove all the prime numbers from the following array and replace it with 0

np.vectorize() - 
Define a vectorized function which takes a nested sequence of objects or numpy arrays as inputs and returns a single numpy array or a tuple of numpy arrays. The vectorized function evaluates `pyfunc` over successive tuples of the input arrays like the python map function, except it uses the broadcasting rules of numpy.

In [157]:
def isprime(number):
    for i in range(2,number):
        if(number%i == 0 and number!=2 ):
            return False
    return True



primecheck = np.vectorize(isprime) ##vectorizes isprime() to be applied on np array
arr = np.arange(2,102).reshape(20,5)

arr[primecheck(arr)]=0
arr

array([[  0,   0,   4,   0,   6],
       [  0,   8,   9,  10,   0],
       [ 12,   0,  14,  15,  16],
       [  0,  18,   0,  20,  21],
       [ 22,   0,  24,  25,  26],
       [ 27,  28,   0,  30,   0],
       [ 32,  33,  34,  35,  36],
       [  0,  38,  39,  40,   0],
       [ 42,   0,  44,  45,  46],
       [  0,  48,  49,  50,  51],
       [ 52,   0,  54,  55,  56],
       [ 57,  58,   0,  60,   0],
       [ 62,  63,  64,  65,  66],
       [  0,  68,  69,  70,   0],
       [ 72,   0,  74,  75,  76],
       [ 77,  78,   0,  80,  81],
       [ 82,   0,  84,  85,  86],
       [ 87,  88,   0,  90,  91],
       [ 92,  93,  94,  95,  96],
       [  0,  98,  99, 100,   0]])

### 4.3 - In the previous array, find the position of all the squares, $1^2, 2^2, 3^2$...

In [195]:
arr = np.arange(2,102).reshape(20,5)

In [196]:
square = np.square(np.arange(1,11))    
print(square)

[  1   4   9  16  25  36  49  64  81 100]


In [197]:
def squarenum(num):
    if num  in square:
        return True
    return False

squarecheck = np.vectorize(squarenum)

In [198]:
arr[squarecheck(arr)] 

array([  4,   9,  16,  25,  36,  49,  64,  81, 100])

In [200]:
arr[squarecheck(arr)]= 0
arr

array([[  2,   3,   0,   5,   6],
       [  7,   8,   0,  10,  11],
       [ 12,  13,  14,  15,   0],
       [ 17,  18,  19,  20,  21],
       [ 22,  23,  24,   0,  26],
       [ 27,  28,  29,  30,  31],
       [ 32,  33,  34,  35,   0],
       [ 37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46],
       [ 47,  48,   0,  50,  51],
       [ 52,  53,  54,  55,  56],
       [ 57,  58,  59,  60,  61],
       [ 62,  63,   0,  65,  66],
       [ 67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,   0],
       [ 82,  83,  84,  85,  86],
       [ 87,  88,  89,  90,  91],
       [ 92,  93,  94,  95,  96],
       [ 97,  98,  99,   0, 101]])

In [201]:
np.where(arr == 0)

(array([ 0,  1,  2,  4,  6,  9, 12, 15, 19], dtype=int64),
 array([2, 2, 4, 3, 4, 2, 2, 4, 3], dtype=int64))

In [203]:
for index,val in np.ndenumerate(arr):
    if val== 0:
        print(index)

(0, 2)
(1, 2)
(2, 4)
(4, 3)
(6, 4)
(9, 2)
(12, 2)
(15, 4)
(19, 3)


Some basic indexing and slicing can be done with the following set of commands:

- arr[:,:] - Returns the sliced portion of the 2D array
- np.where() - Return the indices based on the boolean condition
- np.ndeunmerate() - Returns the values along with it corresponding indices

---
## <font color=blue> Perform operations on Arrays (addition, multiplication etc.)</font>
---

In [204]:
arr1 = np.arange(15).reshape(5,3)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [205]:
#adding a constant
arr1 + 5 

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [206]:
#product using constant
arr1 * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [207]:
arr2 = np.arange(5).reshape(5,1) 
print(arr2)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [208]:
#Matrix sum
print(arr2 + arr1) # arr2[i] + arr1's entire row

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]


In [209]:
#Transpose
arr1.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [210]:
#matrix multiplication
arr1.T @ arr2

array([[ 90],
       [100],
       [110]])

In [211]:
arr3 = np.random.randn(3,5)

In [212]:
# dot product
arr1.dot(arr3)

array([[ -0.,  -2.,   2.,  -5.,  -3.],
       [ -0.,  -1.,   7., -12.,  -6.],
       [ -1.,   1.,  12., -19.,  -9.],
       [ -1.,   3.,  17., -26., -12.],
       [ -1.,   4.,  22., -33., -15.]])

In [213]:
arr = np.random.rand(16).reshape(4,4)

In [214]:
np.linalg.inv(arr)

array([[-1.,  1.,  2., -2.],
       [ 1.,  2.,  0., -2.],
       [-1.,  2.,  0., -0.],
       [ 1., -2., -1.,  2.]])

In [215]:
arr = np.identity(4)
np.linalg.inv(arr)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [216]:
np.ones(5).T @ np.ones(5)

5.0

 ### 5.1 - Verify that `np.linalg.inv()` computes the inverse of a matrix

In [217]:
arr = np.random.rand(3,3)
arr_inv = np.linalg.inv(arr)
arr @ arr_inv

array([[ 1.e+00,  5.e-17,  1.e-16],
       [-3.e-16,  1.e+00,  3.e-16],
       [-6.e-17,  6.e-17,  1.e+00]])

Matrix A= IA , then A * inv A = I

In [219]:
np.set_printoptions(formatter= {"float_kind" : '{:f}'.format})
arr @ arr_inv

array([[1.000000, 0.000000, 0.000000],
       [-0.000000, 1.000000, 0.000000],
       [-0.000000, 0.000000, 1.000000]])

### 5.2 - Extract the row-wise and column-wise sum of the following array

In [221]:
arr = np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [222]:
# row wise sum

np.sum(arr, axis=1)

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [223]:
# column wise sum

np.sum(arr, axis=0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [227]:
# grand total

np.sum(arr)

4950

Numpy is very efficient in performing Matrix operations 

- M1 @ M2 - Multiplies the matrices M1 and M2 - Vector product
- M1.dot(M2) - Performs dot product operation over M1 and M2
- np.linalg.inv() - Calculates the inverse of the matrix

In [224]:
arr = np.arange(100).reshape(10,10)
for index,x in np.ndenumerate(arr):
    if x==50:
        print(index)

(5, 0)


In [225]:
print(np.ones(5) @ np.ones(5).T)

5.0


---
## <font color = blue>Sorting the array</font>
---
### 6.1 `np.sort()`

In [228]:
arr = np.random.randint(1,7, size=[8, 4])
arr

array([[6, 6, 3, 1],
       [2, 5, 1, 3],
       [5, 3, 3, 1],
       [3, 5, 3, 5],
       [2, 5, 1, 3],
       [3, 4, 6, 3],
       [1, 2, 4, 2],
       [2, 2, 3, 1]])

We have a random array of 8 rows and 4 columns.

If you use the np.sort function with axis=0, all the columns will be sorted in ascending order independent of eachother, effectively compromising the integrity of the row items. In simple terms, the values in each row gets corrupted with values from other rows.

In [229]:
# Sort each columns of arr
np.sort(arr, axis=0)

array([[1, 2, 1, 1],
       [2, 2, 1, 1],
       [2, 3, 3, 1],
       [2, 4, 3, 2],
       [3, 5, 3, 3],
       [3, 5, 3, 3],
       [5, 5, 4, 3],
       [6, 6, 6, 5]])

Since I don’t want the content of rows to be disturbed, I resort to an indirect method using np.argsort.

### 6.2 `np.argsort()`

Let’s first understand what np.argsort does.

np.argsort returns the index positions of that would make a given 1d array sorted.



In [230]:
# Get the index positions that would sort the array
x = np.array([1, 10, 5, 2, 8, 9])
sort_index = np.argsort(x)
print(sort_index)

[0 3 2 4 5 1]


How to interpret this?

In array ‘x’, the 0th item is the smallest, 3rd item is the second smallest and so on.

In [231]:
x[sort_index]

array([ 1,  2,  5,  8,  9, 10])

Now, in order to sort the original arr, I am going to do an argsort on the 1st column and use the resulting index positions to sort arr. See the code.

In [232]:
# Argsort the first column
sorted_index_1stcol = arr[:, 0].argsort()

# Sort 'arr' by first column without disturbing the integrity of rows
arr[sorted_index_1stcol]


array([[1, 2, 4, 2],
       [2, 5, 1, 3],
       [2, 5, 1, 3],
       [2, 2, 3, 1],
       [3, 5, 3, 5],
       [3, 4, 6, 3],
       [5, 3, 3, 1],
       [6, 6, 3, 1]])

To sort it in decreasing order, simply reverse the argsorted index.

In [233]:
# Descending sort
arr[sorted_index_1stcol[::-1]]

array([[6, 6, 3, 1],
       [5, 3, 3, 1],
       [3, 4, 6, 3],
       [3, 5, 3, 5],
       [2, 2, 3, 1],
       [2, 5, 1, 3],
       [2, 5, 1, 3],
       [1, 2, 4, 2]])

### 6.3 `np.lexsort()`

In [234]:
# Sort by column 0, then by column 1
lexsorted_index = np.lexsort((arr[:, 1], arr[:, 0])) 
arr[lexsorted_index]

array([[1, 2, 4, 2],
       [2, 2, 3, 1],
       [2, 5, 1, 3],
       [2, 5, 1, 3],
       [3, 4, 6, 3],
       [3, 5, 3, 5],
       [5, 3, 3, 1],
       [6, 6, 3, 1]])

### 6.1 Sort the following array based on the first column, in the descending order

In [235]:
arr = np.random.randint(1,7, size=[8, 4])

sorted_index_1stcol = arr[:, 0].argsort()
arr[sorted_index_1stcol[::-1]]

array([[6, 1, 4, 4],
       [5, 1, 4, 5],
       [4, 6, 6, 3],
       [4, 6, 3, 3],
       [3, 6, 1, 2],
       [3, 4, 3, 2],
       [2, 1, 2, 1],
       [1, 4, 6, 4]])

In [226]:
x = np.array([1,2,3,4,5,6])
sort_index = np.argsort(x)
print(sort_index)

[0 1 2 3 4 5]


Numpy is very efficient in performing sorting
- np.sort() - Sorts all the columns of the matrix - Row information is lost
- np.argsort() - Returns the order of indices on which the rows have to be arranged, based on a singular column
- np.lexsort() - Same as np.argsort() but can be done over multiple columns

---
## <font color=blue> Size of objects in Memory</font>
---


In [236]:
import sys

In [237]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [238]:
sys.getsizeof(10)

28

In [239]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [240]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [241]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [242]:
np.dtype(float).itemsize

8

#### Lists are even larger

In [243]:
# A one-element list
sys.getsizeof([1])

64

In [244]:
# An array of one element in numpy
np.array([1]).nbytes

4

#### And performance is also important


In [2]:
l = list(range(100000))
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [3]:
import numpy as np
a = np.arange(100000)
a

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [4]:
%time np.sum(a ** 2) # Numpy is much faster

Wall time: 394 µs


216474736

In [5]:
%time sum([x ** 2 for x in l])

Wall time: 30.3 ms


333328333350000