# <font color = red> Numpy

In [1]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

---
## <font color = blue> Create a Numpy array</font>
---
    
### 1.1 Using `np.array()`

In [2]:
# Create a numpy array

np_arr = np.array([[11,23,32],[12,34,56],[77,77,54]])
print(np_arr)
print()
print(np_arr.shape)

[[11 23 32]
 [12 34 56]
 [77 77 54]]

(3, 3)


In [3]:
np_arr = np.array([[11,23,32],[12,34,56],[77,77]])
print(np_arr)
print()
print(np_arr.shape)

[list([11, 23, 32]) list([12, 34, 56]) list([77, 77])]

(3,)


In [4]:
np_arr = np.array([[11,23,32],[12,34,56],[77,77,None]])
print(np_arr)
print()
print(np_arr.shape)

[[11 23 32]
 [12 34 56]
 [77 77 None]]

(3, 3)


### 1.2 `np.zeros() and np.ones()`

In [17]:
np_zeros = np.zeros([2,4])
np_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np_ones = np.ones([2,4])
np_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 1.3 `np.full()`

In [19]:
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

### 1.4 `np.arange()`


In [20]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 1.5 `np.linspace()`

the `linspace()` function generates an array with evenly spaced values between specified start, end values, using a specified number of elements

In [22]:
np.linspace(0, 1, 5)

array([0., 0., 0., 1., 1.])

In [23]:
np.linspace(0, 1, 20)
# 20 points equally spaced between 0 and 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [24]:
np.linspace(0, 1, 20, False)
# 20 points equally spaced between 0 and 1, not including 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

### 1.6 `identity`

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.7 `np.random()` 

In [26]:
np.random.random(size=2)
# Return random floats in the half-open interval [0.0, 1.0).
# Results are from the “continuous uniform” distribution over the stated interval.

array([0., 1.])

In [27]:
np.random.normal(size=2)
# creates an array of specified shape and fills it with random values which 
# is actually a part of Normal(Gaussian)Distribution. 
# This is Distribution is also known as Bell Curve because of its characteristics shape.

# https://www.geeksforgeeks.org/rand-vs-normal-numpy-random-python/

array([1., 1.])

In [30]:
arr = np.random.randint(2,10, size =(3,3) )  # 9 random numbers between 2 and 10 in a 3x3 matrix
arr

array([[4, 9, 4],
       [4, 8, 8],
       [9, 9, 4]])

In [33]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([5, 9, 2, 0, 6, 4, 3, 8, 7, 1])

In [35]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.random.shuffle(arr)
arr

array([5, 0, 4, 1, 6, 3, 2, 7, 8, 9])

In [37]:
np.random.rand(2, 4)

array([[1., 0., 1., 1.],
       [0., 0., 1., 0.]])

### 1.1  - Create a 1D array of the first 1000 odd numbers

In [38]:
print(np.linspace(1,1999,1000))

[1.e+00 3.e+00 5.e+00 7.e+00 9.e+00 1.e+01 1.e+01 2.e+01 2.e+01 2.e+01
 2.e+01 2.e+01 2.e+01 3.e+01 3.e+01 3.e+01 3.e+01 4.e+01 4.e+01 4.e+01
 4.e+01 4.e+01 4.e+01 5.e+01 5.e+01 5.e+01 5.e+01 6.e+01 6.e+01 6.e+01
 6.e+01 6.e+01 6.e+01 7.e+01 7.e+01 7.e+01 7.e+01 8.e+01 8.e+01 8.e+01
 8.e+01 8.e+01 8.e+01 9.e+01 9.e+01 9.e+01 9.e+01 1.e+02 1.e+02 1.e+02
 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02
 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02
 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02
 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02
 3.e+0

### 1.2  - Create a 2D array of size (5,10) containing random numbers between 1 and 2

In [39]:
np.random.rand(5,10)+1

array([[1., 1., 1., 2., 2., 2., 2., 2., 1., 1.],
       [2., 2., 2., 2., 1., 1., 1., 2., 2., 1.],
       [1., 1., 1., 2., 1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 2., 1., 1., 1., 2., 2., 1.],
       [2., 1., 2., 2., 2., 1., 1., 2., 2., 2.]])

### 1.3 - Create a 10x10 Identity matrix where all the numbers are in integer format

In [40]:
np.identity(10, dtype='int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

There are multiple ways in which numpy arrays can be created:

- np.array()
- np.ones() / np.zeros()
- np.full()
- np.arange()
- np.linspace()
- np.identity()
- np.random()

---
## <font color = blue> Reshape the array</font>
---    

### 2.1 `np_array.reshape()`

In [41]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
np.arange(12).reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

### 2.2 `arr.flatten()`

In [48]:
arr = np.array([[10,20,30],[40,50,60],[18,18,18]])
print(arr.flatten().shape)
print(arr.flatten())

(9,)
[10 20 30 40 50 60 18 18 18]


In [49]:
type(arr.flatten())

numpy.ndarray

### 2.3 `np.ravel()`

In [50]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [18, 18, 18]])

In [52]:
# Return a contiguous flattened array.

arr_ravel = np.ravel(arr)  
print(arr_ravel)

[10 20 30 40 50 60 18 18 18]


In [56]:
# Row-wise
np.ravel(arr, order='C')

array([10, 20, 30, 40, 50, 60, 18, 18, 18])

In [57]:
# Column-wise
np.ravel(arr, order='F')

array([10, 40, 18, 20, 50, 18, 30, 60, 18])

### 2.1 - Find the transpose of the given array without using `np.transpose`

In [64]:
arr = np.arange(50)
print(arr.shape)

(50,)


In [66]:
arr = arr.reshape(50,1)
print(arr.shape)

(50, 1)


### 2.2 Convert the following 2-D array into a 1-D array in columnar fashion (the first few elements should belong to the first column)

In [68]:
arr = np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
np.ravel(arr, order='F')

array([ 0, 10, 20, 30, 40,  1, 11, 21, 31, 41,  2, 12, 22, 32, 42,  3, 13,
       23, 33, 43,  4, 14, 24, 34, 44,  5, 15, 25, 35, 45,  6, 16, 26, 36,
       46,  7, 17, 27, 37, 47,  8, 18, 28, 38, 48,  9, 19, 29, 39, 49])

The following commands can be used to reshape the array

- np.reshape()
- np.ravel()
- np.flatten()

The one command np.reshape() is enough to perform all reshaping operations. The other two are just good to know if you want to flatten a dataset in a single command, without inspecting it first.

---
## <font color=blue>  Join and stack two arrays</font>
---

- Vertical stacking (row wise) using `vstack()`
- Horizontal stacking (column wise) using `hstack()`
- Depth wise stacking (along third axis) using `dstack()`
- `concatenate()` function creates a new array by appending arrays after each other, along a given axis
- `append()` function appends an element to an array and creates a new copy of the array


In [70]:
import numpy as np


array_1 = np.arange(10).reshape(2,5)
print(array_1)

print("-"*30)

array_2 = np.arange(13,23,1).reshape(2,5)
print(array_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
[[13 14 15 16 17]
 [18 19 20 21 22]]


### 3.1 `np.vstack()`

In [71]:
array_vstack = np.vstack([array_1,array_2])
print(array_vstack)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [13 14 15 16 17]
 [18 19 20 21 22]]


In [72]:
print(array_vstack.shape)

(4, 5)


### 3.2 `np.hstack()`

In [73]:
array_hstack = np.hstack([array_1,array_2])
print(array_hstack)

[[ 0  1  2  3  4 13 14 15 16 17]
 [ 5  6  7  8  9 18 19 20 21 22]]


In [74]:
print(array_hstack.shape)

(2, 10)


### 3.3 `np.dstack()`

In [75]:
array_dstack = np.dstack([array_1,array_2])
print(array_dstack)

[[[ 0 13]
  [ 1 14]
  [ 2 15]
  [ 3 16]
  [ 4 17]]

 [[ 5 18]
  [ 6 19]
  [ 7 20]
  [ 8 21]
  [ 9 22]]]


In [76]:
print(array_dstack.shape) # two sets of 5x2 matrices

(2, 5, 2)


### 3.4 `np.concatenate()`

In [77]:
array_concatenate = np.concatenate([array_1,array_2])
print(array_concatenate)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [13 14 15 16 17]
 [18 19 20 21 22]]


In [78]:
print(array_concatenate.shape) # same as vstack

(4, 5)


### 3.5 `np.append()`

In [79]:
array_append = np.append(array_1,array_2)
print(array_append)

[ 0  1  2  3  4  5  6  7  8  9 13 14 15 16 17 18 19 20 21 22]


In [80]:
print(array_append.shape)

(20,)


In [81]:
array_append = np.append(array_1,array_2,axis =1)
print(array_append)

[[ 0  1  2  3  4 13 14 15 16 17]
 [ 5  6  7  8  9 18 19 20 21 22]]


In [82]:
print(array_append.shape)

(2, 10)


In [83]:
array_append = np.append(array_1,array_2,axis = 0)
print(array_append)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [13 14 15 16 17]
 [18 19 20 21 22]]


In [84]:
print(array_append.shape)

(4, 5)


### 3.1 Represent the chess board as a numpy array
The following are the numerical mapping to chess pieces:
- Pawns: 1
- Rook: 2
- Knight: 3
- Bishop: 4
- King: 5
- Queen: 6
- Empty spaces: 0

In [86]:
row_1 = [2,3,4,5,6,4,3,2]
row_2 = np.ones(8,dtype=int)
row_3_4 = np.zeros(16,dtype=int).reshape(2,8)
top_half = np.vstack([row_1,row_2,row_3_4])
print(top_half)

[[2 3 4 5 6 4 3 2]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [89]:
bottom_half = np.flip(top_half,axis = 0)
print(bottom_half)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [2 3 4 5 6 4 3 2]]


In [85]:
row_1 = [2,3,4,5,6,4,3,2]
row_2 = np.ones(8,dtype=int)
row_3_4 = np.zeros(16,dtype=int).reshape(2,8)
top_half = np.vstack([row_1,row_2,row_3_4])
bottom_half = np.flip(top_half,axis = 0)

chess_board = np.vstack([top_half,bottom_half])
chess_board

array([[2, 3, 4, 5, 6, 4, 3, 2],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 3, 4, 5, 6, 4, 3, 2]])

### 3.2 Create an array of size 10x10 ,where the borders are all ones and the inside elements are zeros

In [105]:
arr = np.zeros(100, dtype=int).reshape(10,10)
print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [106]:
arr[0 , :] = arr[-1 , : ] = arr[ : , 0] = arr[ : , -1] = 1
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [114]:
arr = np.ones(100, dtype=int).reshape(10,10)
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [115]:
arr[1:-1 , 1:-1] = 0
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Any two arrays can be joined in the following formats:
- vstack() - Vertical stacking (row wise)
- hstack() - Horizontal stacking (column wise)
- dstack() - Depth wise stacking (along third axis)
- concatenate() - Creates a new array by appending arrays after each other, along a given axis
- append() - Appends an element to an array and creates a new copy of the array


In [123]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [122]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr.flatten().shape)

(6,)


In [124]:
arr1 = np.array([[0,0],[0,0]])
arr2 = np.array([[1],[1]])
arr3 = np.array([1,1,1])

In [126]:
arr4 = np.hstack([arr1,arr2])
print(np.vstack([arr4,arr3]))

[[0 0 1]
 [0 0 1]
 [1 1 1]]


---
## <font color = blue> Perform basic Slicing and Indexing</font>
---

### 4.1 `Location based indexing`

In [ ]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [ ]:
print(arr[0])

In [ ]:
print(arr[0][0])

In [ ]:
print(arr[0,0])

In [ ]:
print(arr[-1])

In [ ]:
print(arr[:,1:3])

In [ ]:
print(arr[[0,1,2],[1,0,0]])

### 4.2 `Boolean Indexing`

### `np.where(  )`

- Returns the index based on the boolean

### `np.isnan()` 
- Returns the boolean of data == np.nan

In [ ]:
location = np.array(["Mumbai","Mumbai","Delhi","Chennai","Bangalore"]) #2 branches in Mumbai
sales_data = np.random.randint(1,10,size=(5,5))
sales_data = sales_data.astype(float)
sales_data[[[1,4],[2,3]]] = np.nan
print(sales_data)

In [ ]:
sales_data[location =="Mumbai"]
# depending on which index is True, it prints that row
# In this case, mumbai is at index 2, therefore row no. 2 will be printed

In [ ]:
(location =="Mumbai")

In [ ]:
np.where(location == "Mumbai")

In [ ]:
# if the match does not happen , then all values are false.
sales_data[location =="Kolkata"]
# the o/p in such a case is indicating shape as(0 rows, 3 features)

We can also use Boolean indexing for selecting some elements of an array that satisfy a
particular condition. For example, in the previous array suppose we want to only select
non-zero elements.
We can do that easily using the following code.

In [ ]:
sales_data >4

In [ ]:
sales_data == np.nan

`np.nan==np.nan` is always `False`

We use np.isnan() to find out the nan values in the data

In [ ]:
np.isnan(sales_data)

In [ ]:
np.where(np.isnan(sales_data))

In [ ]:
sales_data[np.isnan(sales_data)] = 0.0 # all nan values will be reset to 0
sales_data

### 4.3 `np.ndenumerate()`

ndenumerate return the co-ordinates and corresponding values in the co-ordinates

In [ ]:
A = np.array([[11, 22, 23], [33, 43, 55]])

In [ ]:
np.ndenumerate(A)

In [ ]:
for index, x in np.ndenumerate(A):
    print(index, x)

### 4.1 - Create a 1D array of alternating 0's and 1's of size 500

In [ ]:
#SOLUTION-

arr = np.zeros(500,dtype=int)
arr[1::2]=1
arr

### 4.2 - Remove all the prime numbers from the following array and replace it with 0

In [ ]:
def isprime(number):
    for i in range(2,number):
        if(number%i == 0 and number!=2 ):
            return False
    return True
primecheck = np.vectorize(isprime) ##vectorizes isprime() to be applied on np array
arr = np.arange(2,102).reshape(20,5)


#SOLUTION-

arr[primecheck(arr)]=0
arr

### 4.3 - In the previous array, find the position of all the squares, $1^2, 2^2, 3^2$...

In [ ]:
arr = np.arange(2,102).reshape(20,5)

In [ ]:
#SOLUTION-

    

---
## <font color=blue> Perform operations on Arrays (addition, multiplication etc.)</font>
---

In [ ]:
arr1 = np.arange(15).reshape(5,3)
arr1

In [ ]:
#adding a constant
arr1 + 5 

In [ ]:
#product using constant
arr1 * 2

In [ ]:
arr2 = np.arange(5).reshape(5,1) 
print(arr2)

In [ ]:
#Matrix sum
print(arr2 + arr1) # arr2[i] + arr1's entire row

In [ ]:
#Transpose
arr1.T

In [ ]:
#matrix multiplication
arr1.T @ arr2

In [ ]:
arr3 = np.random.randn(3,5)

In [ ]:
# dot product
arr1.dot(arr3)

In [ ]:
arr = np.random.rand(16).reshape(4,4)

In [ ]:
np.linalg.inv(arr)

In [ ]:
arr = np.identity(4)
np.linalg.inv(arr)

In [ ]:
np.ones(5).T @ np.ones(5)

 ### 5.1 - Verify that `np.linalg.inv()` computes the inverse of a matrix

In [ ]:
#SOLUTION-

arr = np.random.rand(3,3)
arr_inv = np.linalg.inv(arr)
arr @ arr_inv

### 5.2 - Extract the row-wise and column-wise sum of the following array

In [ ]:
arr = np.arange(100).reshape(10,10)

#SOLUTION-
#HINT: Think along the lines of matrix multiplication

---
## <font color = blue>Sorting the array</font>
---
### 6.1 `np.sort()`

In [ ]:
arr = np.random.randint(1,7, size=[8, 4])
arr

We have a random array of 8 rows and 4 columns.

If you use the np.sort function with axis=0, all the columns will be sorted in ascending order independent of eachother, effectively compromising the integrity of the row items. In simple terms, the values in each row gets corrupted with values from other rows.

In [ ]:
# Sort each columns of arr
np.sort(arr, axis=0)

Since I don’t want the content of rows to be disturbed, I resort to an indirect method using np.argsort.

### 6.2 `np.argsort()`

Let’s first understand what np.argsort does.

np.argsort returns the index positions of that would make a given 1d array sorted.



In [ ]:
# Get the index positions that would sort the array
x = np.array([1, 10, 5, 2, 8, 9])
sort_index = np.argsort(x)
print(sort_index)

How to interpret this?

In array ‘x’, the 0th item is the smallest, 3rd item is the second smallest and so on.

In [ ]:
x[sort_index]

Now, in order to sort the original arr, I am going to do an argsort on the 1st column and use the resulting index positions to sort arr. See the code.

In [ ]:
# Argsort the first column
sorted_index_1stcol = arr[:, 0].argsort()

# Sort 'arr' by first column without disturbing the integrity of rows
arr[sorted_index_1stcol]


To sort it in decreasing order, simply reverse the argsorted index.

In [ ]:
# Descending sort
arr[sorted_index_1stcol[::-1]]

### 6.3 `np.lexsort()`

In [ ]:
# Sort by column 0, then by column 1
lexsorted_index = np.lexsort((arr[:, 1], arr[:, 0])) 
arr[lexsorted_index]

### 6.1 Sort the following array based on the first column, in the descending order

In [ ]:
arr = np.random.randint(1,7, size=[8, 4])

#SOLUTION-

---
## <font color=blue> Size of objects in Memory</font>
---


In [ ]:
import sys

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

In [ ]:
sys.getsizeof(10)

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

In [ ]:
np.dtype(float).itemsize

#### Lists are even larger

In [ ]:
# A one-element list
sys.getsizeof([1])

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

#### And performance is also important


In [ ]:
l = list(range(100000))
l

In [ ]:
import numpy as np
a = np.arange(100000)
a

In [ ]:
%time np.sum(a ** 2) # Numpy is much faster

In [ ]:
%time sum([x ** 2 for x in l])